"""Données sportives : compétitions, saisons, équipes, matchs, stats, cotes, ingestions.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 19:56:35.026483
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=60), nullable=False),
        sa.Column("n_teams", sa.SmallInteger(), nullable=False),
        sa.Column("football_data_division", sa.String(length=8), nullable=True),
        sa.Column("understat_slug", sa.String(length=32), nullable=True),
        sa.Column("api_football_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
        sa.UniqueConstraint("code", name=op.f("uq_competitions_code")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "raw_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("football_data", "understat", "api_football", name="data_source"),
            nullable=False,
        ),
        sa.Column("origin", sa.String(length=500), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_files")),
        sa.UniqueConstraint("source", "sha256", name=op.f("uq_raw_files_source")),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("name", name=op.f("uq_teams_name")),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("start_year", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_seasons_competition_id_competitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("competition_id", "start_year", name=op.f("uq_seasons_competition_id")),
    )
    op.create_table(
        "team_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("football_data", "understat", "api_football", name="data_source"),
            nullable=False,
        ),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_aliases_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_aliases")),
        sa.UniqueConstraint("source", "alias", name=op.f("uq_team_aliases_source")),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("match_date", sa.Date(), nullable=False),
        sa.Column("kickoff_time", sa.Time(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("scheduled", "finished", "cancelled", name="match_status"),
            nullable=False,
        ),
        sa.Column("home_goals", sa.SmallInteger(), nullable=True),
        sa.Column("away_goals", sa.SmallInteger(), nullable=True),
        sa.Column("home_goals_ht", sa.SmallInteger(), nullable=True),
        sa.Column("away_goals_ht", sa.SmallInteger(), nullable=True),
        sa.Column("home_shots", sa.SmallInteger(), nullable=True),
        sa.Column("away_shots", sa.SmallInteger(), nullable=True),
        sa.Column("home_shots_on_target", sa.SmallInteger(), nullable=True),
        sa.Column("away_shots_on_target", sa.SmallInteger(), nullable=True),
        sa.Column("home_corners", sa.SmallInteger(), nullable=True),
        sa.Column("away_corners", sa.SmallInteger(), nullable=True),
        sa.Column("home_fouls", sa.SmallInteger(), nullable=True),
        sa.Column("away_fouls", sa.SmallInteger(), nullable=True),
        sa.Column("home_yellow_cards", sa.SmallInteger(), nullable=True),
        sa.Column("away_yellow_cards", sa.SmallInteger(), nullable=True),
        sa.Column("home_red_cards", sa.SmallInteger(), nullable=True),
        sa.Column("away_red_cards", sa.SmallInteger(), nullable=True),
        sa.Column("referee", sa.String(length=100), nullable=True),
        sa.Column("football_data_file_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'finished') = (home_goals IS NOT NULL AND away_goals IS NOT NULL)",
            name=op.f("ck_matches_finished_has_score"),
        ),
        sa.CheckConstraint("home_team_id <> away_team_id", name=op.f("ck_matches_distinct_teams")),
        sa.ForeignKeyConstraint(
            ["away_team_id"], ["teams.id"], name=op.f("fk_matches_away_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["football_data_file_id"],
            ["raw_files.id"],
            name=op.f("fk_matches_football_data_file_id_raw_files"),
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"], ["teams.id"], name=op.f("fk_matches_home_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_matches_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
        sa.UniqueConstraint(
            "season_id", "home_team_id", "away_team_id", name=op.f("uq_matches_season_id")
        ),
    )
    op.create_index(op.f("ix_matches_away_team_id"), "matches", ["away_team_id"], unique=False)
    op.create_index(op.f("ix_matches_home_team_id"), "matches", ["home_team_id"], unique=False)
    op.create_index(op.f("ix_matches_match_date"), "matches", ["match_date"], unique=False)
    op.create_index(op.f("ix_matches_season_id"), "matches", ["season_id"], unique=False)
    op.create_table(
        "match_advanced_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("football_data", "understat", "api_football", name="data_source"),
            nullable=False,
        ),
        sa.Column("source_match_id", sa.String(length=32), nullable=True),
        sa.Column("xg", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("xga", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("npxg", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("npxga", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("ppda_att", sa.SmallInteger(), nullable=True),
        sa.Column("ppda_def", sa.SmallInteger(), nullable=True),
        sa.Column("ppda_allowed_att", sa.SmallInteger(), nullable=True),
        sa.Column("ppda_allowed_def", sa.SmallInteger(), nullable=True),
        sa.Column("deep", sa.SmallInteger(), nullable=True),
        sa.Column("deep_allowed", sa.SmallInteger(), nullable=True),
        sa.Column("xpts", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("raw_file_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_advanced_stats_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_file_id"],
            ["raw_files.id"],
            name=op.f("fk_match_advanced_stats_raw_file_id_raw_files"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_match_advanced_stats_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_advanced_stats")),
        sa.UniqueConstraint(
            "match_id", "team_id", "source", name=op.f("uq_match_advanced_stats_match_id")
        ),
    )
    op.create_index(
        op.f("ix_match_advanced_stats_match_id"), "match_advanced_stats", ["match_id"], unique=False
    )
    op.create_table(
        "match_odds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("football_data", "understat", "api_football", name="data_source"),
            nullable=False,
        ),
        sa.Column("bookmaker", sa.String(length=16), nullable=False),
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("line", sa.Numeric(precision=5, scale=2), server_default="0", nullable=False),
        sa.Column("timing", sa.Enum("pre", "close", name="odds_timing"), nullable=False),
        sa.Column("selection", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.CheckConstraint("price > 1", name=op.f("ck_match_odds_price_above_one")),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_odds_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_odds")),
        sa.UniqueConstraint(
            "match_id",
            "source",
            "bookmaker",
            "market",
            "line",
            "timing",
            "selection",
            name=op.f("uq_match_odds_match_id"),
        ),
    )
    op.create_index(op.f("ix_match_odds_match_id"), "match_odds", ["match_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_odds_match_id"), table_name="match_odds")
    op.drop_table("match_odds")
    op.drop_index(op.f("ix_match_advanced_stats_match_id"), table_name="match_advanced_stats")
    op.drop_table("match_advanced_stats")
    op.drop_index(op.f("ix_matches_season_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_match_date"), table_name="matches")
    op.drop_index(op.f("ix_matches_home_team_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_away_team_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_table("team_aliases")
    op.drop_table("seasons")
    op.drop_table("teams")
    op.drop_table("raw_files")
    op.drop_table("ingestion_runs")
    op.drop_table("competitions")
    # ### end Alembic commands ###
    for enum_name in ("odds_timing", "match_status", "data_source"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
